language: python
services: sqlite
cache:
  directories:
    - $HOME/.cache/pip
before_cache:
  - rm -f $HOME/.cache/pip/log/debug.log
matrix:
    include:
      - python: 2.7
        env: TOX_ENV=py27-django18
      - python: 2.7
        env: TOX_ENV=py27-django19
      - python: 2.7
        env: TOX_ENV=py27-django110
      - python: 2.7
        env: TOX_ENV=py27-django111
      - python: 3.4
        env: TOX_ENV=py34-django18
      - python: 3.4
        env: TOX_ENV=py34-django19
      - python: 3.4
        env: TOX_ENV=py34-django110
      - python: 3.4
        env: TOX_ENV=py34-django111
      - python: 3.4
        env: TOX_ENV=py34-django20
      - python: 3.5
        env: TOX_ENV=py35-django18
      - python: 3.5
        env: TOX_ENV=py35-django19
      - python: 3.5
        env: TOX_ENV=py35-django110
      - python: 3.5
        env: TOX_ENV=py35-django111
      - python: 3.5
        env: TOX_ENV=py35-django20
      - python: 3.6
        env: TOX_ENV=py36-django111
      - python: 3.6
        env: TOX_ENV=py36-django20

script: tox -e $TOX_ENV

install:
    - pip install pip setuptools wheel -U
    - pip install tox
